name: Publish

on:
  push:
    branches:
      - master

jobs:

  # Build the library
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: clean build buildRelease

    - uses: chadly/prod-env-variables@v1
      with:
        keys: |
          GHP_USERNAME
          GHP_TOKEN
      env:
        GHP_USERNAME_PROD: ${{ github.actor }}
        GHP_TOKEN_PROD: ${{ secrets.GITHUB_TOKEN }}

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: publish
